#!/usr/bin/env bash
#script that loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations
school=1
while ((school <= 10));
do
    if ((school == 4));
    then
        echo "bad luck"
    elif ((school == 8));
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((school++));
done
